[profile.default]
src = "contracts/current"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true
# Ignore improvements folder that has missing dependencies
ignore = ["contracts/improvements/**"]

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
